### ISSUE TITLE
New config format

### ISSUE THREAD

**Issue by DavJCosby** [DavJCosby/slc#4]
# Problem

The old config format was never meant to be a permanent solution, just a way to quickly get things running. Here's what my bedroom looked like:
```
60
1.65 0.5
0
2.98 0 3.7084 0
3.7084 0 3.7084 2.86
3.7084 2.86 2.9591 3.6257
2.9536 3.6257 2.3 3
2.3 3 -0.015 3
-0.015 3 -0.015 0
-0.015 0 0.12 0
```

Parsing that into English:
- `60` was the density of the light strips in LEDs/meter
- `1.65 0.5` was the center point. All angle calculations are relative to this 2D point. 
- 0 was the offset angle that would be applied to all angle calculations, in degrees.
- The following lines are all line segments. The numbers in `2.98 0 3.7084 0` are respectively `startX`, `startY`, `endX`, and `endY`. 

As you can see, not super human readable.

# Solution
New config files will use [toml](https://toml.io/en/) and will look like this:

```toml
center_point = [1.65, 0.5]
default_density = 60.0

[[line_segment]]
start = [2.98, 0.0]
end = [3.7084, 0.0]

[[line_segment]]
start = [3.7084, 0.0]
end = [3.7084, 2.86]

[[line_segment]]
start = [3.7084, 2.86]
end = [2.9591, 3.6257]

[[line_segment]]
start = [2.9536, 3.6257]
end = [2.3, 3.0]

[[line_segment]]
start = [2.3, 3.0]
end = [-0.015, 3.0]

[[line_segment]]
start = [2.3, 3.0]
end = [-0.015, 3.0]

[[line_segment]]
start = [2.3, 3.0]
end = [-0.015, 3.0]

[[line_segment]]
start = [-0.015, 3.0]
end = [-0.015, 0.0]

[[line_segment]]
start = [-0.015, 0.0]
end = [0.12, 0.0]
```
Didn't see a good reason to keep angle offsets around.

If one wished for a specific line segment to have a different density from the rest, they can override like this:
```toml
[[line_segment]]
start = [1.5, 0]
end = [1.5, 3.0]
density = 90.0
```

Though this new format gives us much longer configuration files, I believe the added readability is more than worth it.

# To-do
- [x] Set up necessary data structures to represent Config files, Line segments, etc
- [x] Get serialization via serde going
- [x] Support density defaulting and overriding

**Comment by DavJCosby** [comment]
Commit [b1fca72](https://github.com/DavJCosby/slc/commit/b1fca728713b5c87c93f0b82f3689bc95b015599) implements the default density feature described in the original post. Not happy with the solution as it makes use of unsafe blocks, but I'm just not well-versed with serde enough to find a better solution. Worth revisiting.
